
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: view
          
    salesforce:
        vars:
            account: "{{ source('salesforce', 'account') }}"   # or "{{ ref('salesforce_account_unioned'}) }}"
            opportunity: "{{ source('salesforce', 'opportunity') }}" 
            user: "{{ source('salesforce', 'user') }}"
            user_role: "{{ source('salesforce', 'user_role') }}"

    mailchimp:
        vars:
            automation: "{{ source('mailchimp', 'automation') }}"   # or "{{ ref('mailchimp_automations_unioned'}) }}"
            automation_email: "{{ source('mailchimp', 'automation_email') }}" 
            automation_recipient: "{{ source('mailchimp', 'automation_recipient') }}"
            automation_recipient_activity: "{{ source('mailchimp', 'automation_recipient_activity') }}"
            campaign: "{{ source('mailchimp', 'campaign') }}"
            campaign_recipient: "{{ source('mailchimp', 'campaign_recipient') }}"
            campaign_recipient_activity: "{{ source('mailchimp', 'campaign_recipient_activity') }}"
            segment: "{{ source('mailchimp', 'segment') }}"
            segment_member: "{{ source('mailchimp', 'segment_member') }}"
            list: "{{ source('mailchimp', 'list') }}"
            member: "{{ source('mailchimp', 'member') }}"
            unsubscribe: "{{ source('mailchimp', 'unsubscribe') }}"
